#!/bin/bash
#
# symfony project generator
# remember to configure parameters below


# the package source
symfony_package=/Volumes/Macintosh\ Data/Documents/2_TOOLS/symfony/symfony-1.4.11.tgz

# the package directory untarred to be renamed
symfony_version_folder=symfony-1.4.11


if [ ! -f "${symfony_package}" ]; then
	echo error: symfony package not found
	exit
fi


echo "Insert project name:"
read project_name
echo "creating ${project_name}"

mkdir "${project_name}"
cd "${project_name}"
mkdir -p lib/vendor
cd lib/vendor

tar xvvzfp "${symfony_package}"

if [ ! -d "${symfony_version_folder}" ]; then
  echo "wrong symfony folder name"
  exit
fi

mv "${symfony_version_folder}" symfony
cd ..
cd ..
php lib/vendor/symfony/data/bin/symfony generate:project "${project_name}"

echo "Configure database? (y/*)"
read Y

if [ "$Y" == "y" ]; then
	echo "database name:"
	read sf_database

	echo "user:"
	read sf_user

	echo "password:"
	read sf_password
	
	echo php symfony configure:database "mysql:host=localhost;dbname=${sf_database}" ${sf_user} ${sf_password}
	php symfony configure:database "mysql:host=localhost;dbname=${sf_database}" ${sf_user} ${sf_password}
  echo "      attributes:
        default_table_collate: utf8_unicode_ci
        default_table_charset: utf8
									" >> config/databases.yml
fi


echo "Do you want to install additional plugins? (y/*)"
read Y

if [ ! "$Y" == "y" ]; then
	exit
fi

echo "install: sfPHPUnit2Plugin (y/*)"
read Y

if [ "$Y" == "y" ]; then
	echo php symfony plugin:install --stability=beta sfPHPUnit2Plugin
	php symfony plugin:install --stability=beta sfPHPUnit2Plugin
fi


echo "install: sfDoctrineGuardPlugin (y/*)"
read Y

if [ "$Y" == "y" ]; then
	echo php symfony plugin:install sfDoctrineGuardPlugin
	php symfony plugin:install sfDoctrineGuardPlugin
fi
